include:
  - ./admin-panel/compose.yml

  - path: ./telegram-bot/compose.yml
    env_file:
      - .env
      - ./telegram-bot/.env

  - path: ./servers/parser/compose.yml
    env_file:
      - .env
      - ./servers/parser/.env

  - path: ./servers/core/compose.yml
    env_file:
      - .env
      - ./servers/core/.env

  - path: ./servers/knowledge-base/compose.yml
    env_file:
      - .env
      - ./servers/knowledge-base/.env

  - path: ./servers/notify/compose.yml
    env_file:
      - .env
      - ./servers/notify/.env

services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /var/lib/minio-data
    ports:
      - 9000:9001
    volumes:
      - minio-data:/var/lib/minio-data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_ACCESS_KEY}

  kafka:
    image: apache/kafka
    ports:
      - 9001:9092
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka-data

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 9002:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

volumes:
  minio-data:
  kafka-data:
