services:
  client:
    user: root
    build: ./client
    command: npm run dev
    ports:
      - 5010:5010
    volumes:
      - ./client:/opt/client
      - client_node_modules:/opt/client/node_modules

  admin-panel:
    user: root
    build: ./admin-panel
    command: pnpm dev
    ports:
      - 5015:5015
    volumes:
      - ./admin-panel:/opt/admin-panel
      - admin-panel_node_modules:/opt/admin-panel/node_modules

  redis:
    image: redis
    restart: always
    ports:
      - 6397:6379
    volumes:
      - redisdata:/var/lib/redis/data

  bot:
    user: root
    build: ./telegram-bot
    command: bash start.sh
    depends_on:
      redis:
        condition: service_started
      core:
        condition: service_healthy
    volumes:
      - ./telegram-bot:/opt/bot

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5627:5672
      - 15627:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
      retries: 10

  coredb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coredb
    ports:
      - 5423:5432
    volumes:
      - coredata:/var/lib/core/data

  core:
    user: root
    build:
      context: ./servers
      dockerfile: ./core/Dockerfile
    command: dotnet run
    ports:
      - 5000:5000
    depends_on:
      coredb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://core:5000/ping" ]
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - ./servers/core:/opt/core

  parserdb:
    image: mongo
    restart: always
    ports:
      - 27071:27017
    volumes:
      - parserdata:/var/lib/parser/data

  parser:
    user: root
    build: ./servers/parser
    command: python main.py
    depends_on:
      parserdb:
        condition: service_started
    volumes:
      - ./servers/parser:/opt/parser

volumes:
  client_node_modules:
  admin-panel_node_modules:
  redisdata:
  parserdata:
  coredata:
  rabbitmqdata:
