services:
  client:
    build: ./client
    command: npm run dev
    ports:
      - 5010:5010
    volumes:
      - ./client:/opt/client

  bot:
    build: ./telegram-bot
    command: python main.py
    volumes:
      - ./telegram-bot:/opt/bot

  core:
    build: ./servers/core
    command: dotnet run
    ports:
      - 5000:5000
    volumes:
      - ./servers/core:/opt/core

  userdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - 5423:5432
    volumes:
      - userdata:/var/lib/user/data

  user:
    build: ./servers/user
    command: dotnet run
    depends_on:
      userdb:
        condition: service_started
    volumes:
      - ./servers/user:/opt/user

  parserdb:
    image: mongo
    restart: always
    ports:
      - 27071:27017
    volumes:
      - parserdata:/var/lib/parser/data

  parser:
    build: ./servers/parser
    command: python main.py
    depends_on:
      parserdb:
        condition: service_started
    ports:
      - 8000:8000
    volumes:
      - ./servers/parser:/opt/parser

volumes:
  parserdata:
  userdata:
