services:
  client:
    build: ./client
    command: npm run dev
    ports:
      - 5010:5010
    volumes:
      - ./client:/opt/client

  bot:
    build: ./telegram-bot
    command: python main.py
    volumes:
      - ./telegram-bot:/opt/bot

  gateway:
    build: ./servers/gateway
    command: dotnet run
    ports:
      - 5000:5000
    volumes:
      - ./servers/gateway:/opt/gateway

  coredb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coredb
    ports:
      - 5423:5432
    volumes:
      - coredata:/var/lib/core/data

  core:
    build: ./servers/core
    command: dotnet run
    depends_on:
      coredb:
        condition: service_started
    volumes:
      - ./servers/core:/opt/core

  parserdb:
    image: mongo
    restart: always
    ports:
      - 27071:27017
    volumes:
      - parserdata:/var/lib/parser/data

  parser:
    build: ./servers/parser
    command: python main.py
    depends_on:
      parserdb:
        condition: service_started
    ports:
      - 8000:8000
    volumes:
      - ./servers/parser:/opt/parser

volumes:
  parserdata:
  coredata:
