"""versioning3

Revision ID: 60123bc70873
Revises: ecf3a27a98f2
Create Date: 2025-04-16 23:23:15.515460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60123bc70873"
down_revision: Union[str, None] = "ecf3a27a98f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category_versions", "category_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "category_versions_category_id_fkey", "category_versions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "category_versions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "knowledge_item_versions",
        "knowledge_item_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_constraint(
        "knowledge_item_versions_knowledge_item_id_fkey",
        "knowledge_item_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "knowledge_item_versions",
        "knowledge_items",
        ["knowledge_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge_item_versions", type_="foreignkey")
    op.create_foreign_key(
        "knowledge_item_versions_knowledge_item_id_fkey",
        "knowledge_item_versions",
        "knowledge_items",
        ["knowledge_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "knowledge_item_versions",
        "knowledge_item_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_constraint(None, "category_versions", type_="foreignkey")
    op.create_foreign_key(
        "category_versions_category_id_fkey",
        "category_versions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "category_versions", "category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
