services:
  parser-db:
    image: mongo
    ports:
      - 5011:27017
    volumes:
      - parser-db-data:/var/lib/parser-db-data

  parser:
    build: ./
    ports:
      - 5010:8000
    depends_on:
      parser-db:
        condition: service_started
    healthcheck:
      test: "curl --fail http://localhost:8000/ping || exit"
      interval: 10s
      timeout: 30s
      retries: 10
    env_file:
      - .env
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
    volumes:
      - './:/app:z'

volumes:
  parser-db-data:
