services:
  notify-db:
    image: postgres
    ports:
      - 5031:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - notify-db-data:/var/lib/notify-db-data

  notify:
    build: ./
    ports:
      - 5030:5030
    depends_on:
      notify-db:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KAFKA_URL=${KAFKA_URL}
    healthcheck:
      test: "curl --fail http://localhost:5030/healthy || exit"
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - './:/app:z'
      - '/app/bin'
      - '/app/obj'

volumes:
  notify-db-data:
