"""versioning2

Revision ID: ecf3a27a98f2
Revises: 8010a024bdb4
Create Date: 2025-04-16 22:43:20.426997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecf3a27a98f2"
down_revision: Union[str, None] = "8010a024bdb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "category_versions_category_id_fkey", "category_versions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "category_versions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "knowledge_item_versions_knowledge_item_id_fkey",
        "knowledge_item_versions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "knowledge_item_versions_category_id_fkey",
        "knowledge_item_versions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "knowledge_item_versions_deleted_with_category_version_id_fkey",
        "knowledge_item_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "knowledge_item_versions",
        "knowledge_items",
        ["knowledge_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "knowledge_item_versions",
        "category_versions",
        ["deleted_with_category_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "knowledge_item_versions",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge_item_versions", type_="foreignkey")
    op.drop_constraint(None, "knowledge_item_versions", type_="foreignkey")
    op.drop_constraint(None, "knowledge_item_versions", type_="foreignkey")
    op.create_foreign_key(
        "knowledge_item_versions_deleted_with_category_version_id_fkey",
        "knowledge_item_versions",
        "category_versions",
        ["deleted_with_category_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "knowledge_item_versions_category_id_fkey",
        "knowledge_item_versions",
        "categories",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "knowledge_item_versions_knowledge_item_id_fkey",
        "knowledge_item_versions",
        "knowledge_items",
        ["knowledge_item_id"],
        ["id"],
    )
    op.drop_constraint(None, "category_versions", type_="foreignkey")
    op.create_foreign_key(
        "category_versions_category_id_fkey",
        "category_versions",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
