"""tegs_add

Revision ID: 985acca4b8e2
Revises: 858ea5668483
Create Date: 2025-04-16 18:10:53.138130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "985acca4b8e2"
down_revision: Union[str, None] = "858ea5668483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_items",
        sa.Column(
            "question_tags",
            sa.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "knowledge_items",
        sa.Column(
            "answer_tags",
            sa.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_items", "answer_tags")
    op.drop_column("knowledge_items", "question_tags")
    # ### end Alembic commands ###
