services:
  base:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      base-db:
        condition: service_healthy
      base-search:
        condition: service_healthy
    ports:
      - "5020:8080"
    volumes:
      - './app:/knowledge-base/app:z'
    env_file:
      - .env
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  base-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-knowledge-base}
    ports:
      - "5021:5432"
    volumes:
      - base-db-data:/var/lib/base-db-data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DATABASE:-knowledge-base}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  base-search:
    image: elasticsearch:8.17.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-elastic}
      - xpack.security.http.ssl.enabled=${ELASTIC_VERIFY_CERTS:-false}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=ERROR
      - logger.org.elasticsearch=ERROR
      - logger.org.apache.lucene=ERROR
    ports:
      - "5022:9200"
    volumes:
      - base-search-data:/var/lib/base-search-data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -k -u $${ELASTIC_USERNAME:-elastic}:$${ELASTIC_PASSWORD:-elastic} http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  base-db-data:
  base-search-data:
