services:
  bot-db:
    image: redis
    ports:
      - 3001:6379
    volumes:
      - bot-db-data:/data

  bot:
    build: ./
    command: bash start.sh
    ports:
      - 3000:8000
    depends_on:
      bot-db:
        condition: service_started
      core:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
    volumes:
      - './:/app:z'

volumes:
  bot-db-data:
