services:
  bot-db:
    image: redis
    ports:
      - 6397:6379
    volumes:
      - bot-db-data:/var/lib/bot-db-data

  bot:
    build: ./
    command: bash start.sh
    ports:
      - 8001:8000
    depends_on:
      bot-db:
        condition: service_started
      core:
        condition: service_healthy
    volumes:
      - './:/app:z'

volumes:
  bot-db-data:
