services:
  core-db:
    image: postgres
    ports:
      - 5400:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coredb
    volumes:
      - core-db-data:/var/lib/core-db-data

  core-storage:
    image: minio/minio
    command: server --console-address ":9001" /var/lib/core-storage-data
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - core-storage-data:/var/lib/core-storage-data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password

  core:
    build: ./
    ports:
      - 5000:5000
    depends_on:
      core-db:
        condition: service_started
      core-storage:
        condition: service_started
      parser:
        condition: service_healthy
      base:
        condition: service_started
    healthcheck:
      test: "curl --fail http://localhost:5000/healthy || exit"
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - './:/app:z'
      - '/app/bin'
      - '/app/obj'

volumes:
  core-db-data:
  core-storage-data:
