services:
  core-db:
    image: postgres
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - core-db-data:/var/lib/postgresql/data

  core:
    build:
      context: ../
      dockerfile: ./core/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      core-db:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_started
      parser:
        condition: service_healthy
      base:
        condition: service_started
      notify:
        condition: service_healthy
      chat:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KAFKA_URL=${KAFKA_URL}
    healthcheck:
      test: "curl --fail http://localhost:5000/healthy || exit"
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - '../shared:/shared:z'
      - './:/app:z'
      - '/shared/bin'
      - '/shared/obj'
      - '/app/bin'
      - '/app/obj'

volumes:
  core-db-data:
