services:
  core-db:
    image: postgres
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - core-db-data:/var/lib/core-db-data

  core:
    build: ./
    ports:
      - 5000:5000
    depends_on:
      core-db:
        condition: service_started
      minio:
        condition: service_started
      parser:
        condition: service_healthy
      base:
        condition: service_started
    env_file:
      - .env
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - SECRET_TOKEN=${SECRET_TOKEN}
    healthcheck:
      test: "curl --fail http://localhost:5000/healthy || exit"
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - './:/app:z'
      - '/app/bin'
      - '/app/obj'

volumes:
  core-db-data:
